Encode both columns of saveName in the same way
  This fixes a runtime error in Mono under Linux caused by the use of
  Encoding.GetEncoding(932) for the second column of saveName:

  > System.NotSupportedException: Encoding 932 data could not be found.
  > Make sure you have correct international codeset assembly installed
  > and enabled.
  >   (stack trace)